
# development:
#   adapter: redis
#   url: redis://:redispass@redis-10902.c9.us-east-1-4.ec2.cloud.redislabs.com:10902

# test:
#   adapter: async 

# production:
#   adapter: redis
#   url: redis://:redispass@redis-10902.c9.us-east-1-4.ec2.cloud.redislabs.com:10902

# development:
#     adapter: redis
#     url: "redis://#{ENV['DATA_REDIS_HOST']}:6379/1"  

development:
  adapter: redis
  url: redis://198.199.69.82/1     

# test: 
#   adapter: async  

production:
  adapter: redis
  url: "redis://#{ENV['DATA_REDIS_HOST']}:6379/6"    
  
# staging:
#   adapter: redis
#   url: "redis://#{ENV['DATA_REDIS_HOST']}:6379/3"