class AppVariable < ActiveRecord::Migration[5.1]
  def change
    create_table :app_variables do |t|
      t.string :front_end_color, default: "Teal"
      t.string :app_name
      t.string :app_logo
      t.string :app_logo_text
      t.string :app_tab_text
      t.string :app_slogan
      t.string :app_favi
      t.string :app_frontend_logo_text
      t.string :email
      t.string :telephone
      t.string :street
      t.string :city
      t.string :state
      t.string :zip
      t.string :street_2
      t.string :city_2
      t.string :state_2
      t.string :zip_2
      t.text :app_terms
      t.text :app_conditions 
      t.string :theme
      t.string :app_company_name, default: "Margo's Cargo"
      t.string :string_1
      t.string :string_2
      t.string :string_3
      t.string :string_4
      t.string :string_5
      t.string :string_6
      t.string :string_7
      t.string :string_8
      t.string :string_9
      t.string :string_10
      t.string :string_11
      t.string :string_12
      t.string :string_13
      t.string :string_14
      t.string :string_15
      t.string :string_16
      t.string :string_17
      t.string :string_18
      t.string :string_19
      t.string :string_20
      t.string :string_21
      t.string :string_22
      t.string :string_23
      t.string :string_24
      t.string :string_25
      t.string :string_26
      t.string :string_27
      t.string :string_28
      t.string :string_29
      t.string :string_30
      t.text :text_1
      t.text :text_2
      t.text :text_3
      t.text :text_4
      t.text :text_5
      t.text :text_6
      t.text :text_7
      t.text :text_8
      t.text :text_9
      t.text :text_10
      t.text :text_11
      t.text :text_12
      t.text :text_13
      t.text :text_14
      t.text :text_15
      t.text :text_16
      t.text :text_17
      t.text :text_18
      t.text :text_19
      t.text :text_20
      t.string :icon_1
      t.string :icon_2
      t.string :icon_3
      t.string :icon_4
      t.string :icon_5
      t.string :icon_6
      t.string :icon_7
      t.string :icon_8
      t.string :icon_9
      t.string :icon_10
      t.string :icon_11
      t.string :icon_12
      t.string :icon_13
      t.string :icon_14
      t.string :icon_15
      t.string :icon_16
      t.string :icon_17
      t.string :icon_18
      t.string :icon_19
      t.string :icon_20
      t.string :icon_21
      t.string :icon_22
      t.string :icon_23
      t.string :icon_24
      t.string :icon_25
      t.string :icon_26
      t.string :icon_27
      t.string :icon_28
      t.string :icon_29
      t.string :icon_30
      t.timestamps
    end
  end
end
