class Mc < ActiveRecord::Migration[5.1]
  def change
  create_table :mcs do |t|
      t.string :type
      t.string :entity_type
      t.string :operating_status
      t.string :out_of_service_date
      t.string :legal_name
      t.string :dba_name
      t.string :physical_address
      t.string :phone
      t.string :mailing_address
      t.string :usdot_number
      t.string :state_carrier_id_number	 
      t.string :mc_mx_ff_numbers
      t.string :duns_number
      t.string :power_units 	
      t.string :driver_count	
      t.string :mcs_150_form_date
      t.string :mcs_150_mileage_year
      t.string :general_freight
      t.string :household_goods
      t.string :metal_sheets_coils_rolls
      t.string :motor_vehicles
      t.string :drivetow_away
      t.string :logs_poles_beams_lumber
      t.string :building_materials
      t.string :mobile_homes
      t.string :machinery_large_objects
      t.string :fresh_produce
      t.string :safer_layout
      t.string :liquids_gases
      t.string :intermodal 
      t.string :passengers
      t.string :oilfield_equipment
      t.string :livestock
      t.string :grain_feed_hay
      t.string :coal_coke
      t.string :meat
      t.string :garbage_refuse
      t.string :us_mail
      t.string :chemicals
      t.string :commodities_dry_bulk
      t.string :refrigerated_food
      t.string :beverages
      t.string :paper_products
      t.string :utilities
      t.string :agricultural_farm_supplies
      t.string :construction
      t.string :water_well
      t.string :driver_inspections_count
      t.string :vehicle_inspections_count
      t.string :hazmat_inspections_count
      t.string :iep_inspections_count
      t.string :driver_inspections_out_service
      t.string :vehicle_inspections_out_service
      t.string :hazmat_inspections_out_service
      t.string :iep_inspections_out_service
      t.string :driver_inspections_out_service_percent
      t.string :vehicle_inspections_out_service_percent
      t.string :hazmat_inspections_out_service_percent
      t.string :iep_inspections_out_service_percent
      t.string :crash_fatal
      t.string :crash_injury
      t.string :crash_tow
      t.string :crash_total
      t.string :cad_vehicle_inspections
      t.string :cad_driver_inspections
      t.string :cad_vehicle_out_of_service
      t.string :cad_driver_out_of_service
      t.string :cad_vehicle_out_of_service_percent
      t.string :cad_driver_out_of_service_percent
      t.string :us_inspections_prev_24
      t.string :cad_inspections_prev_24
      t.string :crash_results_24_prior 
      t.string :cad_crash_results_24_prior 
      t.string :cad_crash_fatal 
      t.string :cad_crash_injury 
      t.string :cad_crash_tow  
      t.string :cad_crash_total 
      t.string :us_inspection_results_for_24_months_prior_to
      t.string :total_inspections
      t.string :total_iep_inspections
      t.string :crash_inspections
      t.string :the_rating_below_is_current_as_of
      t.string :rating_date 
      t.string :review_date 
      t.string :review_rating
      t.string :review_type
      t.string :company_profile_id, index: true     
      t.timestamps
    end
  end
end
